<?php

namespace Tests\Feature;

use App\Models\Event;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\BaseTestCase;

class EventControllerTest extends BaseTestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function test_create_event()
    {
        $data = [
            'name' => 'First event',
            'address' => $this->faker->address,
        ];
        $response = $this->post('/api/v1/events',$data);

        $response->assertStatus(201);
    }

    /**
     * @test
     */
    public function test_create_event_validation()
    {
        $data = [];
        $response = $this->post('/api/v1/events',$data);

        $response->assertStatus(422);
    }
      /**
     * @test
     */
    public function test_get_all_promo_codes()
    {
        Event::factory(20)->create();
        $response = $this->get('/api/v1/events');

        $response->assertStatus(200);
    }

    /**
     * @test
     */
    public function test_get_all_promo_codes_with_specified_pagination()
    {
        Event::factory(20)->create();
        $response = $this->get('/api/v1/events?paginate=20&status=1');

        $response->assertStatus(200);
    }
}
