<?php

namespace Tests\Feature;

use Tests\BaseTestCase;

class UserControllerTest extends BaseTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function test_create_user()
    {
        $data = [
            'name' => 'John',
            'email' => 'john@example.com',
            'password' => '1234567',
        ];
        $response = $this->post('/api/v1/users',$data);

        $response->assertStatus(201);
    }

    /**
     * @test
     */
    public function test_create_user_validation()
    {
        $data = [];
        $response = $this->post('/api/v1/users',$data);

        $response->assertStatus(422);
    }
}
